name: Deploy .NET App to Azure Web App

on:
  push:
    branches:
      - main  # or your deployment branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # your .NET version

      - name: Restore dependencies (API only)
        run: dotnet restore ./ContactAppNLayer.Api/ContactAppNLayer.Api.csproj

      - name: Build API project only
        run: dotnet build ./ContactAppNLayer.Api/ContactAppNLayer.Api.csproj --configuration Release --no-restore

      - name: Publish API project only
        run: dotnet publish ./ContactAppNLayer.Api/ContactAppNLayer.Api.csproj -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'contactAppapi'   # change to your actual Azure Web App name
          package: ./publish
